name: Debug Smart Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  debug-trigger:
    name: Debug Smart Auto-Merge Trigger
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Debug workflow trigger
        run: |
          echo "🚀 Smart Auto-Merge workflow triggered!"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Draft: ${{ github.event.pull_request.draft }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
      
      - name: Simple comment test
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Debug: Smart Auto-Merge workflow triggered successfully!'
            });